<?php
/**
 * AutomationCampaign
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.222
 * Contact: webservices@constantcontact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConstantContactApi\Client\Model;

use \ArrayAccess;
use \ConstantContactApi\Client\ObjectSerializer;

/**
 * AutomationCampaign Class Doc Comment
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AutomationCampaign implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AutomationCampaign';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'structured_tags' => '\ConstantContactApi\Client\Model\AutomationCampaignStructuredTagsInner[]',
        'active_definition' => '\ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition',
        'draft_definition' => '\ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition',
        'is_name_explicitly_set' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'structured_tags' => null,
        'active_definition' => null,
        'draft_definition' => null,
        'is_name_explicitly_set' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'structured_tags' => false,
        'active_definition' => false,
        'draft_definition' => false,
        'is_name_explicitly_set' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'structured_tags' => 'structured_tags',
        'active_definition' => 'active_definition',
        'draft_definition' => 'draft_definition',
        'is_name_explicitly_set' => 'is_name_explicitly_set'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'structured_tags' => 'setStructuredTags',
        'active_definition' => 'setActiveDefinition',
        'draft_definition' => 'setDraftDefinition',
        'is_name_explicitly_set' => 'setIsNameExplicitlySet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'structured_tags' => 'getStructuredTags',
        'active_definition' => 'getActiveDefinition',
        'draft_definition' => 'getDraftDefinition',
        'is_name_explicitly_set' => 'getIsNameExplicitlySet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('structured_tags', $data ?? [], null);
        $this->setIfExists('active_definition', $data ?? [], null);
        $this->setIfExists('draft_definition', $data ?? [], null);
        $this->setIfExists('is_name_explicitly_set', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The unique identifier for the automation campaign workflow.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the automation campaign.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the automation campaign.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets structured_tags
     *
     * @return \ConstantContactApi\Client\Model\AutomationCampaignStructuredTagsInner[]|null
     */
    public function getStructuredTags()
    {
        return $this->container['structured_tags'];
    }

    /**
     * Sets structured_tags
     *
     * @param \ConstantContactApi\Client\Model\AutomationCampaignStructuredTagsInner[]|null $structured_tags structured_tags
     *
     * @return self
     */
    public function setStructuredTags($structured_tags)
    {
        if (is_null($structured_tags)) {
            throw new \InvalidArgumentException('non-nullable structured_tags cannot be null');
        }
        $this->container['structured_tags'] = $structured_tags;

        return $this;
    }

    /**
     * Gets active_definition
     *
     * @return \ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition|null
     */
    public function getActiveDefinition()
    {
        return $this->container['active_definition'];
    }

    /**
     * Sets active_definition
     *
     * @param \ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition|null $active_definition active_definition
     *
     * @return self
     */
    public function setActiveDefinition($active_definition)
    {
        if (is_null($active_definition)) {
            throw new \InvalidArgumentException('non-nullable active_definition cannot be null');
        }
        $this->container['active_definition'] = $active_definition;

        return $this;
    }

    /**
     * Gets draft_definition
     *
     * @return \ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition|null
     */
    public function getDraftDefinition()
    {
        return $this->container['draft_definition'];
    }

    /**
     * Sets draft_definition
     *
     * @param \ConstantContactApi\Client\Model\AutomationCampaignActiveDefinition|null $draft_definition draft_definition
     *
     * @return self
     */
    public function setDraftDefinition($draft_definition)
    {
        if (is_null($draft_definition)) {
            throw new \InvalidArgumentException('non-nullable draft_definition cannot be null');
        }
        $this->container['draft_definition'] = $draft_definition;

        return $this;
    }

    /**
     * Gets is_name_explicitly_set
     *
     * @return bool|null
     */
    public function getIsNameExplicitlySet()
    {
        return $this->container['is_name_explicitly_set'];
    }

    /**
     * Sets is_name_explicitly_set
     *
     * @param bool|null $is_name_explicitly_set Indicates whether the automation campaign name was explicitly set.
     *
     * @return self
     */
    public function setIsNameExplicitlySet($is_name_explicitly_set)
    {
        if (is_null($is_name_explicitly_set)) {
            throw new \InvalidArgumentException('non-nullable is_name_explicitly_set cannot be null');
        }
        $this->container['is_name_explicitly_set'] = $is_name_explicitly_set;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


