<?php
/**
 * DetailedRegistrationDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.222
 * Contact: webservices@constantcontact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConstantContactApi\Client\Model;

use \ArrayAccess;
use \ConstantContactApi\Client\ObjectSerializer;

/**
 * DetailedRegistrationDto Class Doc Comment
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DetailedRegistrationDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DetailedRegistrationDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'registration_id' => 'string',
        'contact_id' => 'string',
        'checked_in_tickets' => 'int',
        'checkin_status' => 'string',
        'eligible_checkin_tickets' => 'int',
        'registration_date' => '\DateTime',
        'registration_status' => 'string',
        'display_physical_tickets' => 'bool',
        'contact' => '\ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseContactInner[]',
        'tickets' => '\ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseTicketsInner[]',
        'order_summary' => '\ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseOrderSummary'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'registration_id' => null,
        'contact_id' => null,
        'checked_in_tickets' => 'int32',
        'checkin_status' => null,
        'eligible_checkin_tickets' => 'int32',
        'registration_date' => 'date-time',
        'registration_status' => null,
        'display_physical_tickets' => null,
        'contact' => null,
        'tickets' => null,
        'order_summary' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'registration_id' => false,
        'contact_id' => false,
        'checked_in_tickets' => false,
        'checkin_status' => false,
        'eligible_checkin_tickets' => false,
        'registration_date' => false,
        'registration_status' => false,
        'display_physical_tickets' => false,
        'contact' => false,
        'tickets' => false,
        'order_summary' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'registration_id' => 'registration_id',
        'contact_id' => 'contact_id',
        'checked_in_tickets' => 'checkedIn_tickets',
        'checkin_status' => 'checkin_status',
        'eligible_checkin_tickets' => 'eligible_checkin_tickets',
        'registration_date' => 'registration_date',
        'registration_status' => 'registration_status',
        'display_physical_tickets' => 'display_physical_tickets',
        'contact' => 'contact',
        'tickets' => 'tickets',
        'order_summary' => 'order_summary'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'registration_id' => 'setRegistrationId',
        'contact_id' => 'setContactId',
        'checked_in_tickets' => 'setCheckedInTickets',
        'checkin_status' => 'setCheckinStatus',
        'eligible_checkin_tickets' => 'setEligibleCheckinTickets',
        'registration_date' => 'setRegistrationDate',
        'registration_status' => 'setRegistrationStatus',
        'display_physical_tickets' => 'setDisplayPhysicalTickets',
        'contact' => 'setContact',
        'tickets' => 'setTickets',
        'order_summary' => 'setOrderSummary'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'registration_id' => 'getRegistrationId',
        'contact_id' => 'getContactId',
        'checked_in_tickets' => 'getCheckedInTickets',
        'checkin_status' => 'getCheckinStatus',
        'eligible_checkin_tickets' => 'getEligibleCheckinTickets',
        'registration_date' => 'getRegistrationDate',
        'registration_status' => 'getRegistrationStatus',
        'display_physical_tickets' => 'getDisplayPhysicalTickets',
        'contact' => 'getContact',
        'tickets' => 'getTickets',
        'order_summary' => 'getOrderSummary'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('registration_id', $data ?? [], null);
        $this->setIfExists('contact_id', $data ?? [], null);
        $this->setIfExists('checked_in_tickets', $data ?? [], null);
        $this->setIfExists('checkin_status', $data ?? [], null);
        $this->setIfExists('eligible_checkin_tickets', $data ?? [], null);
        $this->setIfExists('registration_date', $data ?? [], null);
        $this->setIfExists('registration_status', $data ?? [], null);
        $this->setIfExists('display_physical_tickets', $data ?? [], null);
        $this->setIfExists('contact', $data ?? [], null);
        $this->setIfExists('tickets', $data ?? [], null);
        $this->setIfExists('order_summary', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets registration_id
     *
     * @return string|null
     */
    public function getRegistrationId()
    {
        return $this->container['registration_id'];
    }

    /**
     * Sets registration_id
     *
     * @param string|null $registration_id The unique ID used to identify an event registration.
     *
     * @return self
     */
    public function setRegistrationId($registration_id)
    {
        if (is_null($registration_id)) {
            throw new \InvalidArgumentException('non-nullable registration_id cannot be null');
        }
        $this->container['registration_id'] = $registration_id;

        return $this;
    }

    /**
     * Gets contact_id
     *
     * @return string|null
     */
    public function getContactId()
    {
        return $this->container['contact_id'];
    }

    /**
     * Sets contact_id
     *
     * @param string|null $contact_id The unique ID used to identify a contact.
     *
     * @return self
     */
    public function setContactId($contact_id)
    {
        if (is_null($contact_id)) {
            throw new \InvalidArgumentException('non-nullable contact_id cannot be null');
        }
        $this->container['contact_id'] = $contact_id;

        return $this;
    }

    /**
     * Gets checked_in_tickets
     *
     * @return int|null
     */
    public function getCheckedInTickets()
    {
        return $this->container['checked_in_tickets'];
    }

    /**
     * Sets checked_in_tickets
     *
     * @param int|null $checked_in_tickets The total number of tickets assigned to a given <code>registration_id</code>.
     *
     * @return self
     */
    public function setCheckedInTickets($checked_in_tickets)
    {
        if (is_null($checked_in_tickets)) {
            throw new \InvalidArgumentException('non-nullable checked_in_tickets cannot be null');
        }
        $this->container['checked_in_tickets'] = $checked_in_tickets;

        return $this;
    }

    /**
     * Gets checkin_status
     *
     * @return string|null
     */
    public function getCheckinStatus()
    {
        return $this->container['checkin_status'];
    }

    /**
     * Sets checkin_status
     *
     * @param string|null $checkin_status Provides the status of eligible checkin tickets.
     *
     * @return self
     */
    public function setCheckinStatus($checkin_status)
    {
        if (is_null($checkin_status)) {
            throw new \InvalidArgumentException('non-nullable checkin_status cannot be null');
        }
        $this->container['checkin_status'] = $checkin_status;

        return $this;
    }

    /**
     * Gets eligible_checkin_tickets
     *
     * @return int|null
     */
    public function getEligibleCheckinTickets()
    {
        return $this->container['eligible_checkin_tickets'];
    }

    /**
     * Sets eligible_checkin_tickets
     *
     * @param int|null $eligible_checkin_tickets The total number of tickets eligible for checkin.
     *
     * @return self
     */
    public function setEligibleCheckinTickets($eligible_checkin_tickets)
    {
        if (is_null($eligible_checkin_tickets)) {
            throw new \InvalidArgumentException('non-nullable eligible_checkin_tickets cannot be null');
        }
        $this->container['eligible_checkin_tickets'] = $eligible_checkin_tickets;

        return $this;
    }

    /**
     * Gets registration_date
     *
     * @return \DateTime|null
     */
    public function getRegistrationDate()
    {
        return $this->container['registration_date'];
    }

    /**
     * Sets registration_date
     *
     * @param \DateTime|null $registration_date The event registration date, in ISO format.
     *
     * @return self
     */
    public function setRegistrationDate($registration_date)
    {
        if (is_null($registration_date)) {
            throw new \InvalidArgumentException('non-nullable registration_date cannot be null');
        }
        $this->container['registration_date'] = $registration_date;

        return $this;
    }

    /**
     * Gets registration_status
     *
     * @return string|null
     */
    public function getRegistrationStatus()
    {
        return $this->container['registration_status'];
    }

    /**
     * Sets registration_status
     *
     * @param string|null $registration_status Provides the current registration status; <code>REGISTERED</code>, <code>PENDING</code>, <code>CANCELED</code>, <code>EXPIRED</code>, <code>IN_PROGRESS</code>, <code>FAILED</code>.
     *
     * @return self
     */
    public function setRegistrationStatus($registration_status)
    {
        if (is_null($registration_status)) {
            throw new \InvalidArgumentException('non-nullable registration_status cannot be null');
        }
        $this->container['registration_status'] = $registration_status;

        return $this;
    }

    /**
     * Gets display_physical_tickets
     *
     * @return bool|null
     */
    public function getDisplayPhysicalTickets()
    {
        return $this->container['display_physical_tickets'];
    }

    /**
     * Sets display_physical_tickets
     *
     * @param bool|null $display_physical_tickets Determines if the physical tickets should display or not display.
     *
     * @return self
     */
    public function setDisplayPhysicalTickets($display_physical_tickets)
    {
        if (is_null($display_physical_tickets)) {
            throw new \InvalidArgumentException('non-nullable display_physical_tickets cannot be null');
        }
        $this->container['display_physical_tickets'] = $display_physical_tickets;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseContactInner[]|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseContactInner[]|null $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {
        if (is_null($contact)) {
            throw new \InvalidArgumentException('non-nullable contact cannot be null');
        }
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets tickets
     *
     * @return \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseTicketsInner[]|null
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets
     *
     * @param \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseTicketsInner[]|null $tickets tickets
     *
     * @return self
     */
    public function setTickets($tickets)
    {
        if (is_null($tickets)) {
            throw new \InvalidArgumentException('non-nullable tickets cannot be null');
        }
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Gets order_summary
     *
     * @return \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseOrderSummary|null
     */
    public function getOrderSummary()
    {
        return $this->container['order_summary'];
    }

    /**
     * Sets order_summary
     *
     * @param \ConstantContactApi\Client\Model\GetRegistrationInfo200ResponseOrderSummary|null $order_summary order_summary
     *
     * @return self
     */
    public function setOrderSummary($order_summary)
    {
        if (is_null($order_summary)) {
            throw new \InvalidArgumentException('non-nullable order_summary cannot be null');
        }
        $this->container['order_summary'] = $order_summary;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


