<?php
/**
 * EmailCampaignAccountInformation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.222
 * Contact: webservices@constantcontact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConstantContactApi\Client\Model;

use \ArrayAccess;
use \ConstantContactApi\Client\ObjectSerializer;

/**
 * EmailCampaignAccountInformation Class Doc Comment
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmailCampaignAccountInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmailCampaignAccountInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'first_name' => 'string',
        'last_name' => 'string',
        'physical_address' => '\ConstantContactApi\Client\Model\EmailCampaignAccountInformationPhysicalAddress',
        'website' => 'string',
        'community_screen_name' => 'string',
        'logo_url' => 'string',
        'contact_email' => 'string',
        'contact_phone' => 'string',
        'verified_emails' => 'string[]',
        'all_emails' => 'string[]',
        'message_settings' => '\ConstantContactApi\Client\Model\EmailCampaignAccountInformationMessageSettings',
        'timezone' => 'string',
        'phone_prefix' => 'string',
        'phone_remainder' => 'string',
        'organization_phone' => 'string',
        'industry_type' => 'string',
        'locale' => 'string',
        'last_authenticated_email' => 'string',
        'use_source_account_images' => 'bool',
        'default_from_email' => 'string',
        'reply_to_email' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'first_name' => null,
        'last_name' => null,
        'physical_address' => null,
        'website' => null,
        'community_screen_name' => null,
        'logo_url' => null,
        'contact_email' => 'email',
        'contact_phone' => null,
        'verified_emails' => null,
        'all_emails' => null,
        'message_settings' => null,
        'timezone' => null,
        'phone_prefix' => null,
        'phone_remainder' => null,
        'organization_phone' => null,
        'industry_type' => null,
        'locale' => null,
        'last_authenticated_email' => 'email',
        'use_source_account_images' => null,
        'default_from_email' => 'email',
        'reply_to_email' => 'email'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'first_name' => false,
        'last_name' => false,
        'physical_address' => false,
        'website' => false,
        'community_screen_name' => false,
        'logo_url' => false,
        'contact_email' => false,
        'contact_phone' => false,
        'verified_emails' => false,
        'all_emails' => false,
        'message_settings' => false,
        'timezone' => false,
        'phone_prefix' => false,
        'phone_remainder' => false,
        'organization_phone' => false,
        'industry_type' => false,
        'locale' => false,
        'last_authenticated_email' => false,
        'use_source_account_images' => false,
        'default_from_email' => false,
        'reply_to_email' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'physical_address' => 'physical_address',
        'website' => 'website',
        'community_screen_name' => 'community_screen_name',
        'logo_url' => 'logo_url',
        'contact_email' => 'contact_email',
        'contact_phone' => 'contact_phone',
        'verified_emails' => 'verified_emails',
        'all_emails' => 'all_emails',
        'message_settings' => 'message_settings',
        'timezone' => 'timezone',
        'phone_prefix' => 'phone_prefix',
        'phone_remainder' => 'phone_remainder',
        'organization_phone' => 'organization_phone',
        'industry_type' => 'industry_type',
        'locale' => 'locale',
        'last_authenticated_email' => 'last_authenticated_email',
        'use_source_account_images' => 'use_source_account_images',
        'default_from_email' => 'default_from_email',
        'reply_to_email' => 'reply_to_email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'physical_address' => 'setPhysicalAddress',
        'website' => 'setWebsite',
        'community_screen_name' => 'setCommunityScreenName',
        'logo_url' => 'setLogoUrl',
        'contact_email' => 'setContactEmail',
        'contact_phone' => 'setContactPhone',
        'verified_emails' => 'setVerifiedEmails',
        'all_emails' => 'setAllEmails',
        'message_settings' => 'setMessageSettings',
        'timezone' => 'setTimezone',
        'phone_prefix' => 'setPhonePrefix',
        'phone_remainder' => 'setPhoneRemainder',
        'organization_phone' => 'setOrganizationPhone',
        'industry_type' => 'setIndustryType',
        'locale' => 'setLocale',
        'last_authenticated_email' => 'setLastAuthenticatedEmail',
        'use_source_account_images' => 'setUseSourceAccountImages',
        'default_from_email' => 'setDefaultFromEmail',
        'reply_to_email' => 'setReplyToEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'physical_address' => 'getPhysicalAddress',
        'website' => 'getWebsite',
        'community_screen_name' => 'getCommunityScreenName',
        'logo_url' => 'getLogoUrl',
        'contact_email' => 'getContactEmail',
        'contact_phone' => 'getContactPhone',
        'verified_emails' => 'getVerifiedEmails',
        'all_emails' => 'getAllEmails',
        'message_settings' => 'getMessageSettings',
        'timezone' => 'getTimezone',
        'phone_prefix' => 'getPhonePrefix',
        'phone_remainder' => 'getPhoneRemainder',
        'organization_phone' => 'getOrganizationPhone',
        'industry_type' => 'getIndustryType',
        'locale' => 'getLocale',
        'last_authenticated_email' => 'getLastAuthenticatedEmail',
        'use_source_account_images' => 'getUseSourceAccountImages',
        'default_from_email' => 'getDefaultFromEmail',
        'reply_to_email' => 'getReplyToEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('physical_address', $data ?? [], null);
        $this->setIfExists('website', $data ?? [], null);
        $this->setIfExists('community_screen_name', $data ?? [], null);
        $this->setIfExists('logo_url', $data ?? [], null);
        $this->setIfExists('contact_email', $data ?? [], null);
        $this->setIfExists('contact_phone', $data ?? [], null);
        $this->setIfExists('verified_emails', $data ?? [], null);
        $this->setIfExists('all_emails', $data ?? [], null);
        $this->setIfExists('message_settings', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('phone_prefix', $data ?? [], null);
        $this->setIfExists('phone_remainder', $data ?? [], null);
        $this->setIfExists('organization_phone', $data ?? [], null);
        $this->setIfExists('industry_type', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('last_authenticated_email', $data ?? [], null);
        $this->setIfExists('use_source_account_images', $data ?? [], null);
        $this->setIfExists('default_from_email', $data ?? [], null);
        $this->setIfExists('reply_to_email', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name Account owner's first name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name Account owner's last name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets physical_address
     *
     * @return \ConstantContactApi\Client\Model\EmailCampaignAccountInformationPhysicalAddress|null
     */
    public function getPhysicalAddress()
    {
        return $this->container['physical_address'];
    }

    /**
     * Sets physical_address
     *
     * @param \ConstantContactApi\Client\Model\EmailCampaignAccountInformationPhysicalAddress|null $physical_address physical_address
     *
     * @return self
     */
    public function setPhysicalAddress($physical_address)
    {
        if (is_null($physical_address)) {
            throw new \InvalidArgumentException('non-nullable physical_address cannot be null');
        }
        $this->container['physical_address'] = $physical_address;

        return $this;
    }

    /**
     * Gets website
     *
     * @return string|null
     */
    public function getWebsite()
    {
        return $this->container['website'];
    }

    /**
     * Sets website
     *
     * @param string|null $website Account website URL
     *
     * @return self
     */
    public function setWebsite($website)
    {
        if (is_null($website)) {
            throw new \InvalidArgumentException('non-nullable website cannot be null');
        }
        $this->container['website'] = $website;

        return $this;
    }

    /**
     * Gets community_screen_name
     *
     * @return string|null
     */
    public function getCommunityScreenName()
    {
        return $this->container['community_screen_name'];
    }

    /**
     * Sets community_screen_name
     *
     * @param string|null $community_screen_name Community screen name for the account
     *
     * @return self
     */
    public function setCommunityScreenName($community_screen_name)
    {
        if (is_null($community_screen_name)) {
            throw new \InvalidArgumentException('non-nullable community_screen_name cannot be null');
        }
        $this->container['community_screen_name'] = $community_screen_name;

        return $this;
    }

    /**
     * Gets logo_url
     *
     * @return string|null
     */
    public function getLogoUrl()
    {
        return $this->container['logo_url'];
    }

    /**
     * Sets logo_url
     *
     * @param string|null $logo_url URL for the account logo
     *
     * @return self
     */
    public function setLogoUrl($logo_url)
    {
        if (is_null($logo_url)) {
            throw new \InvalidArgumentException('non-nullable logo_url cannot be null');
        }
        $this->container['logo_url'] = $logo_url;

        return $this;
    }

    /**
     * Gets contact_email
     *
     * @return string|null
     */
    public function getContactEmail()
    {
        return $this->container['contact_email'];
    }

    /**
     * Sets contact_email
     *
     * @param string|null $contact_email Primary contact email address
     *
     * @return self
     */
    public function setContactEmail($contact_email)
    {
        if (is_null($contact_email)) {
            throw new \InvalidArgumentException('non-nullable contact_email cannot be null');
        }
        $this->container['contact_email'] = $contact_email;

        return $this;
    }

    /**
     * Gets contact_phone
     *
     * @return string|null
     */
    public function getContactPhone()
    {
        return $this->container['contact_phone'];
    }

    /**
     * Sets contact_phone
     *
     * @param string|null $contact_phone Primary contact phone number
     *
     * @return self
     */
    public function setContactPhone($contact_phone)
    {
        if (is_null($contact_phone)) {
            throw new \InvalidArgumentException('non-nullable contact_phone cannot be null');
        }
        $this->container['contact_phone'] = $contact_phone;

        return $this;
    }

    /**
     * Gets verified_emails
     *
     * @return string[]|null
     */
    public function getVerifiedEmails()
    {
        return $this->container['verified_emails'];
    }

    /**
     * Sets verified_emails
     *
     * @param string[]|null $verified_emails List of verified email addresses. You must verify an email address before you can use it as the from address in an email.
     *
     * @return self
     */
    public function setVerifiedEmails($verified_emails)
    {
        if (is_null($verified_emails)) {
            throw new \InvalidArgumentException('non-nullable verified_emails cannot be null');
        }
        $this->container['verified_emails'] = $verified_emails;

        return $this;
    }

    /**
     * Gets all_emails
     *
     * @return string[]|null
     */
    public function getAllEmails()
    {
        return $this->container['all_emails'];
    }

    /**
     * Sets all_emails
     *
     * @param string[]|null $all_emails List of all email addresses associated with the account
     *
     * @return self
     */
    public function setAllEmails($all_emails)
    {
        if (is_null($all_emails)) {
            throw new \InvalidArgumentException('non-nullable all_emails cannot be null');
        }
        $this->container['all_emails'] = $all_emails;

        return $this;
    }

    /**
     * Gets message_settings
     *
     * @return \ConstantContactApi\Client\Model\EmailCampaignAccountInformationMessageSettings|null
     */
    public function getMessageSettings()
    {
        return $this->container['message_settings'];
    }

    /**
     * Sets message_settings
     *
     * @param \ConstantContactApi\Client\Model\EmailCampaignAccountInformationMessageSettings|null $message_settings message_settings
     *
     * @return self
     */
    public function setMessageSettings($message_settings)
    {
        if (is_null($message_settings)) {
            throw new \InvalidArgumentException('non-nullable message_settings cannot be null');
        }
        $this->container['message_settings'] = $message_settings;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone Account timezone
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets phone_prefix
     *
     * @return string|null
     */
    public function getPhonePrefix()
    {
        return $this->container['phone_prefix'];
    }

    /**
     * Sets phone_prefix
     *
     * @param string|null $phone_prefix Phone number prefix
     *
     * @return self
     */
    public function setPhonePrefix($phone_prefix)
    {
        if (is_null($phone_prefix)) {
            throw new \InvalidArgumentException('non-nullable phone_prefix cannot be null');
        }
        $this->container['phone_prefix'] = $phone_prefix;

        return $this;
    }

    /**
     * Gets phone_remainder
     *
     * @return string|null
     */
    public function getPhoneRemainder()
    {
        return $this->container['phone_remainder'];
    }

    /**
     * Sets phone_remainder
     *
     * @param string|null $phone_remainder Phone number remainder
     *
     * @return self
     */
    public function setPhoneRemainder($phone_remainder)
    {
        if (is_null($phone_remainder)) {
            throw new \InvalidArgumentException('non-nullable phone_remainder cannot be null');
        }
        $this->container['phone_remainder'] = $phone_remainder;

        return $this;
    }

    /**
     * Gets organization_phone
     *
     * @return string|null
     */
    public function getOrganizationPhone()
    {
        return $this->container['organization_phone'];
    }

    /**
     * Sets organization_phone
     *
     * @param string|null $organization_phone Organization phone number
     *
     * @return self
     */
    public function setOrganizationPhone($organization_phone)
    {
        if (is_null($organization_phone)) {
            throw new \InvalidArgumentException('non-nullable organization_phone cannot be null');
        }
        $this->container['organization_phone'] = $organization_phone;

        return $this;
    }

    /**
     * Gets industry_type
     *
     * @return string|null
     */
    public function getIndustryType()
    {
        return $this->container['industry_type'];
    }

    /**
     * Sets industry_type
     *
     * @param string|null $industry_type Industry type classification
     *
     * @return self
     */
    public function setIndustryType($industry_type)
    {
        if (is_null($industry_type)) {
            throw new \InvalidArgumentException('non-nullable industry_type cannot be null');
        }
        $this->container['industry_type'] = $industry_type;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale Account locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets last_authenticated_email
     *
     * @return string|null
     */
    public function getLastAuthenticatedEmail()
    {
        return $this->container['last_authenticated_email'];
    }

    /**
     * Sets last_authenticated_email
     *
     * @param string|null $last_authenticated_email Last email address used for authentication
     *
     * @return self
     */
    public function setLastAuthenticatedEmail($last_authenticated_email)
    {
        if (is_null($last_authenticated_email)) {
            throw new \InvalidArgumentException('non-nullable last_authenticated_email cannot be null');
        }
        $this->container['last_authenticated_email'] = $last_authenticated_email;

        return $this;
    }

    /**
     * Gets use_source_account_images
     *
     * @return bool|null
     */
    public function getUseSourceAccountImages()
    {
        return $this->container['use_source_account_images'];
    }

    /**
     * Sets use_source_account_images
     *
     * @param bool|null $use_source_account_images Indicates if source account images should be used
     *
     * @return self
     */
    public function setUseSourceAccountImages($use_source_account_images)
    {
        if (is_null($use_source_account_images)) {
            throw new \InvalidArgumentException('non-nullable use_source_account_images cannot be null');
        }
        $this->container['use_source_account_images'] = $use_source_account_images;

        return $this;
    }

    /**
     * Gets default_from_email
     *
     * @return string|null
     */
    public function getDefaultFromEmail()
    {
        return $this->container['default_from_email'];
    }

    /**
     * Sets default_from_email
     *
     * @param string|null $default_from_email Default from email address
     *
     * @return self
     */
    public function setDefaultFromEmail($default_from_email)
    {
        if (is_null($default_from_email)) {
            throw new \InvalidArgumentException('non-nullable default_from_email cannot be null');
        }
        $this->container['default_from_email'] = $default_from_email;

        return $this;
    }

    /**
     * Gets reply_to_email
     *
     * @return string|null
     */
    public function getReplyToEmail()
    {
        return $this->container['reply_to_email'];
    }

    /**
     * Sets reply_to_email
     *
     * @param string|null $reply_to_email Default reply-to email address
     *
     * @return self
     */
    public function setReplyToEmail($reply_to_email)
    {
        if (is_null($reply_to_email)) {
            throw new \InvalidArgumentException('non-nullable reply_to_email cannot be null');
        }
        $this->container['reply_to_email'] = $reply_to_email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


