<?php
/**
 * EventSettingsDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Constant Contact API v3
 *
 * Swagger build version 3.0.161
 *
 * The version of the OpenAPI document: 1.0.222
 * Contact: webservices@constantcontact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConstantContactApi\Client\Model;

use \ArrayAccess;
use \ConstantContactApi\Client\ObjectSerializer;

/**
 * EventSettingsDto Class Doc Comment
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventSettingsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EventSettingsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'event_requires_payments' => 'bool',
        'item_configured' => 'bool',
        'online_payment_configured' => 'bool',
        'payment_configured' => 'bool',
        'promo_code_configured' => 'bool',
        'ticket_configured' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'event_requires_payments' => null,
        'item_configured' => null,
        'online_payment_configured' => null,
        'payment_configured' => null,
        'promo_code_configured' => null,
        'ticket_configured' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'event_requires_payments' => false,
        'item_configured' => false,
        'online_payment_configured' => false,
        'payment_configured' => false,
        'promo_code_configured' => false,
        'ticket_configured' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'event_requires_payments' => 'event_requires_payments',
        'item_configured' => 'item_configured',
        'online_payment_configured' => 'online_payment_configured',
        'payment_configured' => 'payment_configured',
        'promo_code_configured' => 'promo_code_configured',
        'ticket_configured' => 'ticket_configured'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'event_requires_payments' => 'setEventRequiresPayments',
        'item_configured' => 'setItemConfigured',
        'online_payment_configured' => 'setOnlinePaymentConfigured',
        'payment_configured' => 'setPaymentConfigured',
        'promo_code_configured' => 'setPromoCodeConfigured',
        'ticket_configured' => 'setTicketConfigured'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'event_requires_payments' => 'getEventRequiresPayments',
        'item_configured' => 'getItemConfigured',
        'online_payment_configured' => 'getOnlinePaymentConfigured',
        'payment_configured' => 'getPaymentConfigured',
        'promo_code_configured' => 'getPromoCodeConfigured',
        'ticket_configured' => 'getTicketConfigured'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('event_requires_payments', $data ?? [], null);
        $this->setIfExists('item_configured', $data ?? [], null);
        $this->setIfExists('online_payment_configured', $data ?? [], null);
        $this->setIfExists('payment_configured', $data ?? [], null);
        $this->setIfExists('promo_code_configured', $data ?? [], null);
        $this->setIfExists('ticket_configured', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event_requires_payments
     *
     * @return bool|null
     */
    public function getEventRequiresPayments()
    {
        return $this->container['event_requires_payments'];
    }

    /**
     * Sets event_requires_payments
     *
     * @param bool|null $event_requires_payments Specifies if the event is configured to require payment.
     *
     * @return self
     */
    public function setEventRequiresPayments($event_requires_payments)
    {
        if (is_null($event_requires_payments)) {
            throw new \InvalidArgumentException('non-nullable event_requires_payments cannot be null');
        }
        $this->container['event_requires_payments'] = $event_requires_payments;

        return $this;
    }

    /**
     * Gets item_configured
     *
     * @return bool|null
     */
    public function getItemConfigured()
    {
        return $this->container['item_configured'];
    }

    /**
     * Sets item_configured
     *
     * @param bool|null $item_configured Specifies if items exist for the event.
     *
     * @return self
     */
    public function setItemConfigured($item_configured)
    {
        if (is_null($item_configured)) {
            throw new \InvalidArgumentException('non-nullable item_configured cannot be null');
        }
        $this->container['item_configured'] = $item_configured;

        return $this;
    }

    /**
     * Gets online_payment_configured
     *
     * @return bool|null
     */
    public function getOnlinePaymentConfigured()
    {
        return $this->container['online_payment_configured'];
    }

    /**
     * Sets online_payment_configured
     *
     * @param bool|null $online_payment_configured Specifies if online payment is configured for the event.
     *
     * @return self
     */
    public function setOnlinePaymentConfigured($online_payment_configured)
    {
        if (is_null($online_payment_configured)) {
            throw new \InvalidArgumentException('non-nullable online_payment_configured cannot be null');
        }
        $this->container['online_payment_configured'] = $online_payment_configured;

        return $this;
    }

    /**
     * Gets payment_configured
     *
     * @return bool|null
     */
    public function getPaymentConfigured()
    {
        return $this->container['payment_configured'];
    }

    /**
     * Sets payment_configured
     *
     * @param bool|null $payment_configured Specifies if payment is configured for the event.
     *
     * @return self
     */
    public function setPaymentConfigured($payment_configured)
    {
        if (is_null($payment_configured)) {
            throw new \InvalidArgumentException('non-nullable payment_configured cannot be null');
        }
        $this->container['payment_configured'] = $payment_configured;

        return $this;
    }

    /**
     * Gets promo_code_configured
     *
     * @return bool|null
     */
    public function getPromoCodeConfigured()
    {
        return $this->container['promo_code_configured'];
    }

    /**
     * Sets promo_code_configured
     *
     * @param bool|null $promo_code_configured Specifies if promo code is configured for the event.
     *
     * @return self
     */
    public function setPromoCodeConfigured($promo_code_configured)
    {
        if (is_null($promo_code_configured)) {
            throw new \InvalidArgumentException('non-nullable promo_code_configured cannot be null');
        }
        $this->container['promo_code_configured'] = $promo_code_configured;

        return $this;
    }

    /**
     * Gets ticket_configured
     *
     * @return bool|null
     */
    public function getTicketConfigured()
    {
        return $this->container['ticket_configured'];
    }

    /**
     * Sets ticket_configured
     *
     * @param bool|null $ticket_configured Specifies if ticketing is configured for the event
     *
     * @return self
     */
    public function setTicketConfigured($ticket_configured)
    {
        if (is_null($ticket_configured)) {
            throw new \InvalidArgumentException('non-nullable ticket_configured cannot be null');
        }
        $this->container['ticket_configured'] = $ticket_configured;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


