<?php
/**
 * GetEmailCampaignReport200ResponseBulkEmailCampaignSummariesInnerUniqueCounts
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Constant Contact API v3
 *
 * Swagger build version 3.0.53
 *
 * The version of the OpenAPI document: 1.0.170
 * Contact: webservices@constantcontact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ConstantContactApi\Client\Model;

use \ArrayAccess;
use \ConstantContactApi\Client\ObjectSerializer;

/**
 * GetEmailCampaignReport200ResponseBulkEmailCampaignSummariesInnerUniqueCounts Class Doc Comment
 *
 * @category Class
 * @description The total number of times each unique contact interacted with a tracked email campaign activity.
 * @package  ConstantContactApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetEmailCampaignReport200ResponseBulkEmailCampaignSummariesInnerUniqueCounts implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getEmailCampaignReport_200_response_bulk_email_campaign_summaries_inner_unique_counts';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sends' => 'int',
        'opens' => 'int',
        'clicks' => 'int',
        'forwards' => 'int',
        'optouts' => 'int',
        'abuse' => 'int',
        'bounces' => 'int',
        'not_opened' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sends' => 'int32',
        'opens' => 'int32',
        'clicks' => 'int32',
        'forwards' => 'int32',
        'optouts' => 'int32',
        'abuse' => 'int32',
        'bounces' => 'int32',
        'not_opened' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sends' => false,
        'opens' => false,
        'clicks' => false,
        'forwards' => false,
        'optouts' => false,
        'abuse' => false,
        'bounces' => false,
        'not_opened' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sends' => 'sends',
        'opens' => 'opens',
        'clicks' => 'clicks',
        'forwards' => 'forwards',
        'optouts' => 'optouts',
        'abuse' => 'abuse',
        'bounces' => 'bounces',
        'not_opened' => 'not_opened'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sends' => 'setSends',
        'opens' => 'setOpens',
        'clicks' => 'setClicks',
        'forwards' => 'setForwards',
        'optouts' => 'setOptouts',
        'abuse' => 'setAbuse',
        'bounces' => 'setBounces',
        'not_opened' => 'setNotOpened'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sends' => 'getSends',
        'opens' => 'getOpens',
        'clicks' => 'getClicks',
        'forwards' => 'getForwards',
        'optouts' => 'getOptouts',
        'abuse' => 'getAbuse',
        'bounces' => 'getBounces',
        'not_opened' => 'getNotOpened'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sends', $data ?? [], null);
        $this->setIfExists('opens', $data ?? [], null);
        $this->setIfExists('clicks', $data ?? [], null);
        $this->setIfExists('forwards', $data ?? [], null);
        $this->setIfExists('optouts', $data ?? [], null);
        $this->setIfExists('abuse', $data ?? [], null);
        $this->setIfExists('bounces', $data ?? [], null);
        $this->setIfExists('not_opened', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sends'] === null) {
            $invalidProperties[] = "'sends' can't be null";
        }
        if ($this->container['opens'] === null) {
            $invalidProperties[] = "'opens' can't be null";
        }
        if ($this->container['clicks'] === null) {
            $invalidProperties[] = "'clicks' can't be null";
        }
        if ($this->container['forwards'] === null) {
            $invalidProperties[] = "'forwards' can't be null";
        }
        if ($this->container['optouts'] === null) {
            $invalidProperties[] = "'optouts' can't be null";
        }
        if ($this->container['abuse'] === null) {
            $invalidProperties[] = "'abuse' can't be null";
        }
        if ($this->container['bounces'] === null) {
            $invalidProperties[] = "'bounces' can't be null";
        }
        if ($this->container['not_opened'] === null) {
            $invalidProperties[] = "'not_opened' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sends
     *
     * @return int
     */
    public function getSends()
    {
        return $this->container['sends'];
    }

    /**
     * Sets sends
     *
     * @param int $sends The total number of unique sends.
     *
     * @return self
     */
    public function setSends($sends)
    {
        if (is_null($sends)) {
            throw new \InvalidArgumentException('non-nullable sends cannot be null');
        }
        $this->container['sends'] = $sends;

        return $this;
    }

    /**
     * Gets opens
     *
     * @return int
     */
    public function getOpens()
    {
        return $this->container['opens'];
    }

    /**
     * Sets opens
     *
     * @param int $opens The total number of unique opens.
     *
     * @return self
     */
    public function setOpens($opens)
    {
        if (is_null($opens)) {
            throw new \InvalidArgumentException('non-nullable opens cannot be null');
        }
        $this->container['opens'] = $opens;

        return $this;
    }

    /**
     * Gets clicks
     *
     * @return int
     */
    public function getClicks()
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     *
     * @param int $clicks The total number of unique clicks.
     *
     * @return self
     */
    public function setClicks($clicks)
    {
        if (is_null($clicks)) {
            throw new \InvalidArgumentException('non-nullable clicks cannot be null');
        }
        $this->container['clicks'] = $clicks;

        return $this;
    }

    /**
     * Gets forwards
     *
     * @return int
     */
    public function getForwards()
    {
        return $this->container['forwards'];
    }

    /**
     * Sets forwards
     *
     * @param int $forwards The total number of unique forwards.
     *
     * @return self
     */
    public function setForwards($forwards)
    {
        if (is_null($forwards)) {
            throw new \InvalidArgumentException('non-nullable forwards cannot be null');
        }
        $this->container['forwards'] = $forwards;

        return $this;
    }

    /**
     * Gets optouts
     *
     * @return int
     */
    public function getOptouts()
    {
        return $this->container['optouts'];
    }

    /**
     * Sets optouts
     *
     * @param int $optouts The total number of unique optouts (unsubscribes).
     *
     * @return self
     */
    public function setOptouts($optouts)
    {
        if (is_null($optouts)) {
            throw new \InvalidArgumentException('non-nullable optouts cannot be null');
        }
        $this->container['optouts'] = $optouts;

        return $this;
    }

    /**
     * Gets abuse
     *
     * @return int
     */
    public function getAbuse()
    {
        return $this->container['abuse'];
    }

    /**
     * Sets abuse
     *
     * @param int $abuse The total number of unique abuse count (spam).
     *
     * @return self
     */
    public function setAbuse($abuse)
    {
        if (is_null($abuse)) {
            throw new \InvalidArgumentException('non-nullable abuse cannot be null');
        }
        $this->container['abuse'] = $abuse;

        return $this;
    }

    /**
     * Gets bounces
     *
     * @return int
     */
    public function getBounces()
    {
        return $this->container['bounces'];
    }

    /**
     * Sets bounces
     *
     * @param int $bounces The total number of unique bounce count.
     *
     * @return self
     */
    public function setBounces($bounces)
    {
        if (is_null($bounces)) {
            throw new \InvalidArgumentException('non-nullable bounces cannot be null');
        }
        $this->container['bounces'] = $bounces;

        return $this;
    }

    /**
     * Gets not_opened
     *
     * @return int
     */
    public function getNotOpened()
    {
        return $this->container['not_opened'];
    }

    /**
     * Sets not_opened
     *
     * @param int $not_opened The total number of unique non-opens
     *
     * @return self
     */
    public function setNotOpened($not_opened)
    {
        if (is_null($not_opened)) {
            throw new \InvalidArgumentException('non-nullable not_opened cannot be null');
        }
        $this->container['not_opened'] = $not_opened;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


